import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Providers> {children}
            <Toaster
              position="bottom-right"
              toastOptions={{
                className: "bg-gradient-to-br from-emerald-600 to-teal-600  text-white",
                style: {
                  background: "rgba(0, 0, 0, 0.8)",
                  color: "white",
                  borderRadius: "0.5rem",
                  padding: "0.5rem",
                  fontSize: "0.875rem",
                },
              }}

            />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
